### PR TITLE
Added gitignore; Added livereload; Converted GF to coffeescript

### PR DESCRIPTION
**Pull request by rex**

### CODE REVIEW

**Comment by galenandrew** [comment]
Hmm… @rex converting to coffeescript seems a bit opinionated in this context. User-base for Javascript is much larger and more univerally accepted. I would recommend either 1) adding an alternative GF written in coffeescript or 2) leverage a coffeescript GF in your own implementation of the project…not in the upstream source of an OS repo.

**Comment by Klanders85** [comment]
@rex thanks for the PR! Agree with @galenandrew on this one, mainly because I am not familiar enough with CoffeeScript to merge.

**Comment by galenandrew** [comment]
+1 for the `.gitignore` file though. @rex open a new PR with that!

**Comment by rex** [comment]
@galenandrew @Klanders85 Only reason I converted Gruntfile to coffeescript was that the internal implementation of Grunt doesn't care. You still run Grunt with the `grunt` command, and internally Grunt looks for a `Gruntfile.js` and then a `Gruntfile.coffee` if the JS isn't found. At that point, it just comes down to preference. You can't have both, and I think that most people who have spent enough time configuring Grunt would appreciate it being in coffeescript. Ultimately it's just a config object and there's absolutely no reason to prefer the standard JS syntax.

**Pull request closed without merging**
